#Phần 1: Khám phá Tensor

## # Task 1.1: Tạo Tensor

In [8]:
import torch
import numpy as np

# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n{x_data}\n")

# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n{x_np}\n")

# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data)  # tạo tensor gồm toàn 1, cùng shape
print(f"Ones Tensor:\n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n{x_rand}\n")

# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")


Tensor từ list:
tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
tensor([[1, 2],
        [3, 4]])

Ones Tensor:
tensor([[1, 1],
        [1, 1]])

Random Tensor:
tensor([[0.6267, 0.6849],
        [0.8107, 0.5239]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


## Task 1.2: Các phép toán trên Tensor

In [9]:
import torch

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data, dtype=torch.float)

# 1. Cộng x_data với chính nó
add_result = x_data + x_data
print(f"Cộng x_data với chính nó:\n{add_result}\n")

# 2. Nhân x_data với 5
mul_result = x_data * 5
print(f"Nhân x_data với 5:\n{mul_result}\n")

# 3. Nhân ma trận x_data với x_data.T
matmul_result = x_data @ x_data.T
print(f"Nhân ma trận x_data với x_data.T:\n{matmul_result}")


Cộng x_data với chính nó:
tensor([[2., 4.],
        [6., 8.]])

Nhân x_data với 5:
tensor([[ 5., 10.],
        [15., 20.]])

Nhân ma trận x_data với x_data.T:
tensor([[ 5., 11.],
        [11., 25.]])


## Task 1.3: Indexing và Slicing

In [10]:
import torch

x_data = torch.tensor([[1, 2], [3, 4]])

# 1. Lấy ra hàng đầu tiên
first_row = x_data[0]
print(f"Hàng đầu tiên: {first_row}")

# 2. Lấy ra cột thứ hai
second_col = x_data[:, 1]
print(f"Cột thứ hai: {second_col}")

# 3. Lấy ra giá trị ở hàng thứ hai, cột thứ hai
value_22 = x_data[1, 1]
print(f"Giá trị tại (2,2): {value_22}")


Hàng đầu tiên: tensor([1, 2])
Cột thứ hai: tensor([2, 4])
Giá trị tại (2,2): 4


## Task 1.4: Thay đổi hình dạng Tensor

In [11]:
import torch

x = torch.rand(4, 4)
print(f"Tensor ban đầu (4x4):\n{x}\n")

reshaped = x.view(16, 1)
print(f"Tensor sau khi reshape thành (16x1):\n{reshaped}")


Tensor ban đầu (4x4):
tensor([[0.8610, 0.6586, 0.9890, 0.6545],
        [0.0434, 0.2106, 0.6556, 0.8412],
        [0.2154, 0.1645, 0.5989, 0.4789],
        [0.0361, 0.6517, 0.6137, 0.2758]])

Tensor sau khi reshape thành (16x1):
tensor([[0.8610],
        [0.6586],
        [0.9890],
        [0.6545],
        [0.0434],
        [0.2106],
        [0.6556],
        [0.8412],
        [0.2154],
        [0.1645],
        [0.5989],
        [0.4789],
        [0.0361],
        [0.6517],
        [0.6137],
        [0.2758]])


# 2. Tự động tính Đạo hàm với autograd

## Task 2.1: Tự động tính đạo hàm với autograd

In [12]:
import torch

# Tạo một tensor và yêu cầu tính đạo hàm
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

# Thực hiện phép toán
y = x + 2
print(f"y: {y}")
print(f"grad_fn của y: {y.grad_fn}")

# Thực hiện thêm phép toán
z = y * y * 3

# Tính đạo hàm của z theo x
z.backward()

print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x7ee5ffce9360>
Đạo hàm của z theo x: tensor([18.])


# 3. Xây dựng Mô hình đầu tiên với torch.nn

# Task 3.1: Lớp nn.Linear

In [13]:
import torch

# Khởi tạo lớp Linear 5 -> 2
linear_layer = torch.nn.Linear(in_features=5, out_features=2)

# Tạo đầu vào mẫu
input_tensor = torch.randn(3, 5)  # 3 mẫu, mỗi mẫu 5 chiều
output = linear_layer(input_tensor)

print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n{output}")


Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
tensor([[-0.3336, -0.2342],
        [ 0.0435,  0.6797],
        [-0.8468,  0.4001]], grad_fn=<AddmmBackward0>)


# Task 3.2: Lớp nn.Embedding

In [14]:
import torch

# Tạo lớp Embedding cho 10 từ, mỗi từ biểu diễn bằng vector 3 chiều
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

# Tạo tensor chỉ số từ (mỗi giá trị < 10)
input_indices = torch.LongTensor([1, 5, 0, 8])

# Lấy vector embedding tương ứng
embeddings = embedding_layer(input_indices)

print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n{embeddings}")


Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
tensor([[ 1.9784,  1.0431,  0.0301],
        [ 1.0138, -0.1661, -0.6852],
        [ 1.0022,  0.9331, -0.6132],
        [ 0.6162, -0.3981,  0.9029]], grad_fn=<EmbeddingBackward0>)


# Task 3.3: Kết hợp thành một nn.Module

In [15]:
import torch
from torch import nn

class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU()
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        embeds = self.embedding(indices)
        hidden = self.activation(self.linear(embeds))
        output = self.output_layer(hidden)
        return output

# Khởi tạo mô hình
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)

# Dữ liệu đầu vào mẫu
input_data = torch.LongTensor([[1, 2, 5, 9]])
output_data = model(input_data)

print(f"Model output shape: {output_data.shape}")
print(f"Model output:\n{output_data}")


Model output shape: torch.Size([1, 4, 2])
Model output:
tensor([[[ 0.2238, -0.1658],
         [-0.2160, -0.0153],
         [ 0.1426, -0.1605],
         [ 0.5413, -0.3138]]], grad_fn=<ViewBackward0>)
